### ISSUE TITLE
As a user, I expect the events to be synced timely, to not miss any changes.

### ISSUE THREAD

**Issue by ohnewein** [idm-suedtirol/NOI-display#1]
- [x] activate synchronisation over the API as a continous job

**Comment by RudiThoeni** [comment]
in what time interval the sync has to be done

**Comment by ohnewein** [comment]
Ideally the changes become visible in real time. Can we have a refresh every minute?

**Comment by RudiThoeni** [comment]
a sync every minute???? Since there is no chance to get only changed items from the Eurac Interface, i have to update 500 events every minute..... Inserted events in the cms are displayed immediately........ the sync is only for Events managed by Eurac..... In my opinion a sync every minute is total overkill that causes only a lack of server performance........don'T forget the whole suedtirol.info data is on this server.......... I don't think Eurac is managing so many updates of Events

**Comment by RudiThoeni** [comment]
I think we can first ask Verena on usually how many times there are done last minute changes.........

**Comment by ohnewein** [comment]
What would be a reasonable sync interval in your view?
